### PR TITLE
Add expandActionRoot/expandStateRoot props

### PR DESCRIPTION
**Pull request by romanmatiasko**
As mentioned in #9, it would be nice to have ability to set action/state roots in JSON tree to collapsed/not expanded via props.

**react-json-tree** takes additional `expandRoot` prop from v0.3.0, so this is fairly easy.

I added two new props to **LogMonitor**, `expandActionRoot` and `expandStateRoot` that are set to `true` by default, but can be explicitly set to `false`.

Since `collapsed` prop name was already taken and refers to **LogMonitorEntry**, I decided to name them similar to **react-json-tree** prop name. I think they are less ambiguous.

### CODE REVIEW

**Comment by henrybaxter** [comment]
Ah I did it in #24 but this is better. Clearly we want it, can we get some feedback @gaearon?

**Comment by gaearon** [comment]
This looks great. Can you please also document it in README?

**Comment by romanmatiasko** [comment]
Thanks, README has been updated.

**Comment by jasonslyvia** [comment]
Cool feature! Please consider merge this.

**Comment by henrybaxter** [comment]
Yes, please consider adding this, I think it's a simple and very useful change

**Comment by gaearon** [comment]
Out in 1.0.2, thank you very much!

**Pull request merged**
