### PR TITLE
Fix PropTypes deprecation warnings

### PR DESCRIPTION
**Pull request by koox00**

### CODE REVIEW

**Comment by borm** [comment]
It is possible after this pull request has accepted
https://github.com/alexkuz/react-json-tree/pull/77

**Comment by borm** [comment]
I think it will be easier if the react leaves all the same in itself this package
Https://github.com/facebook/react/issues/9418

**Comment by mlynam** [comment]
Any word on this PR?  My console OCD is lit right now.

**Comment by swaggy** [comment]
Will this be merged soon?

**Comment by mbifulco** [comment]
@borm the [PR referenced above](alexkuz/react-json-tree#77) was closed and released this morning 👍 

Anything else holding this back? It looks like this PR will fix #64

**Comment by borm** [comment]
@mbifulco, log-monitor no longer dependencies, wait when be closed #64

**Comment by zalmoxisus** [comment]
Thanks for the contribution! It's published as `1.3.0`. Also `redux-devtools@1.3.0`.

**Pull request merged**
